### ISSUE TITLE
Why do you choose Resilience4j

### ISSUE THREAD

**Issue by HelloTo4x** [awakelife93/spring-boot-api-gateway#2]
Hi, i am reading your project, i have a question, why do u choose Resilience4j instead of Hystrix for Circuit Breaker ? Can u tell me the pros and cons of Resilienece4j

**Comment by awakelife93** [comment]
Hello.

The reason why I chose Resilience4j is that Hystrix is deprecated.

I haven't used Resilience4j a lot, but the good thing is... It is designed with a functional programming technique based on Java 8. So, it was very good that it was relatively easy to apply to the system.

And it provides a lot of functionality.
ex: Circuit Breaker, retry, Rate limiting...

I don't know the downside yet, but what I felt while writing it was that the more API, the harder it was to manage.

Thank you.
